"""
qa_router.py — Q&A Endpoints
==============================
Endpoints:
  POST /api/v1/qa/ask                              — Ask a question (full pipeline)
  GET  /api/v1/qa/ask/stream                       — Ask with streaming response
  POST /api/v1/qa/sessions                         — Create a Q&A session
  GET  /api/v1/qa/sessions                         — List user's sessions
  GET  /api/v1/qa/sessions/{id}/messages           — Messages in a session
  DELETE /api/v1/qa/sessions/{id}                  — Delete a session
  GET  /api/v1/qa/messages/{id}                    — Get single message with sources
  PATCH /api/v1/qa/messages/{id}/feedback          — Submit helpful/not helpful feedback
  PATCH /api/v1/qa/messages/{id}/validate          — Admin validates answer
  GET  /api/v1/qa/history                          — All Q&A history (admin)
  GET  /api/v1/qa/ai-logs                          — AI call logs (admin)
"""

from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.security import get_current_user, require_role
from app.schemas.schemas import (
    AskQuestionRequest, FeedbackRequest, ValidationRequest,
    SessionCreate, SessionOut, SessionListOut,
    QAMessageOut, QAMessageListOut, AILogOut,
)
from app.services.qa_service import QAService
from app.utils.response import ResponseBuilder

from app.core.security import get_current_user
from app.models.models import User

router = APIRouter(prefix="/qa", tags=["Q&A"])


# ─────────────────────────────────────────────────────────────────────────────
# ASK A QUESTION
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/ask", summary="Ask a question to the Knowledge Base")
async def ask_question(
    request: AskQuestionRequest,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """
    Main Q&A endpoint. Full pipeline:
      1. Semantic search for relevant document chunks
      2. Gemini 2.5 Flash generates a grounded answer
      3. Answer + source references saved to DB

    Request body:
        - question:   The natural language question (min 5 chars)
        - session_id: Optional — pass to continue an existing chat session.
                      If omitted, a new session is created automatically.

    Returns:
        QA message with answer, source chunks, and session info.
    """
    service = QAService(db)
    role_name = current_user.role.name if current_user.role else "viewer"
    # Allow unpublished access if admin AND request explicitly asks for it
    is_privileged = role_name in ["admin"]
    allow_unpublished = is_privileged and (request.allow_unpublished or False)
    message = await service.ask_question(
        request,
        user_id=current_user.id,
        allow_unpublished=allow_unpublished,
    )
    return ResponseBuilder.success(
        data=QAMessageOut.model_validate(message).model_dump(mode="json"),
        message="Answer generated successfully.",
        status_code=201,
    )


@router.get("/ask/stream", summary="Ask with real-time streaming response")
async def ask_question_stream(
    question: str = Query(..., min_length=5, description="Your question"),
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """
    Streaming version of the Q&A endpoint.
    Returns text/event-stream — tokens are sent as they are generated by Gemini.
    The answer is NOT saved to the database in this mode (use /ask for persistence).

    Query params:
        - question: The natural language question

    Returns:
        Server-Sent Events (SSE) stream of partial answer tokens.
    """
    from app.ai.ai_agent import stream_question

    async def event_generator():
        try:
            async for token in stream_question(question):
                # SSE format: "data: <token>\n\n"
                yield f"data: {token}\n\n"
            yield "data: [DONE]\n\n"
        except Exception as exc:
            yield f"data: [ERROR] {str(exc)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


# ─────────────────────────────────────────────────────────────────────────────
# SESSIONS
# ─────────────────────────────────────────────────────────────────────────────

@router.post("/sessions", summary="Create a new Q&A session")
async def create_session(
    data: SessionCreate,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """
    Creates a new chat session for organising related questions.

    Request body:
        - title: Optional session name (default: 'New Session')

    Returns:
        Created session record.
    """
    service = QAService(db)
    session = await service.create_session(data, user_id=current_user.id)
    return ResponseBuilder.success(
        data=SessionOut.model_validate(session).model_dump(mode="json"),
        message="Session created successfully.",
        status_code=201,
    )


@router.get("/sessions", summary="List user's Q&A sessions")
async def list_sessions(
    page:       int           = Query(default=1,    ge=1),
    page_size:  int           = Query(default=10,   ge=1, le=100),
    search:     Optional[str] = Query(default=None),
    sort_by:    str           = Query(default="created_at"),
    sort_order: str           = Query(default="desc", pattern="^(asc|desc)$"),
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """Returns the authenticated user's Q&A sessions, paginated."""
    service = QAService(db)
    items, total = await service.list_sessions(
        current_user.id, page, page_size, search, sort_by, sort_order
    )
    out = [SessionListOut.model_validate(s).model_dump(mode="json") for s in items]
    return ResponseBuilder.paginated(items=out, total=total, page=page, page_size=page_size)


@router.delete("/sessions/{session_id}", summary="Delete a Q&A session")
async def delete_session(
    session_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """Soft-deletes a Q&A session and all its messages."""
    service = QAService(db)
    await service.delete_session(session_id, current_user.id)
    return ResponseBuilder.success(message="Session deleted successfully.")


@router.get("/sessions/{session_id}/messages", summary="Get messages in a session")
async def list_session_messages(
    session_id: UUID,
    page:       int = Query(default=1,  ge=1),
    page_size:  int = Query(default=20, ge=1, le=100),
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """
    Returns paginated messages for a specific session.
    Messages are ordered oldest-first (chat order).
    Only the session owner can view messages.
    """
    service = QAService(db)
    items, total = await service.list_messages(session_id, current_user.id, page, page_size)
    out = [QAMessageOut.model_validate(m).model_dump(mode="json") for m in items]
    return ResponseBuilder.paginated(items=out, total=total, page=page, page_size=page_size)


# ─────────────────────────────────────────────────────────────────────────────
# MESSAGES
# ─────────────────────────────────────────────────────────────────────────────

@router.get("/messages/{message_id}", summary="Get a single Q&A message with sources")
async def get_message(
    message_id: UUID,
    db: AsyncSession = Depends(get_db),
    _=Depends(get_current_user),
):
    """Returns a single Q&A message including its source document chunks."""
    service = QAService(db)
    message = await service.get_message(message_id)
    return ResponseBuilder.success(
        data=QAMessageOut.model_validate(message).model_dump(mode="json"),
        message="Message fetched successfully.",
    )


@router.patch("/messages/{message_id}/feedback", summary="Submit helpful / not helpful feedback")
async def submit_feedback(
    message_id: UUID,
    feedback: FeedbackRequest,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """
    Records user feedback on an AI answer.

    Request body:
        - helpful: true (thumbs up) or false (thumbs down)

    Returns:
        Updated message with helpful field set.
    """
    service = QAService(db)
    message = await service.submit_feedback(message_id, feedback, current_user.id)
    return ResponseBuilder.success(
        data=QAMessageOut.model_validate(message).model_dump(mode="json"),
        message="Feedback recorded. Thank you!",
    )


@router.patch("/messages/{message_id}/validate", summary="Admin validates an AI answer")
async def validate_message(
    message_id: UUID,
    data: ValidationRequest,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(require_role("admin")),
):
    """
    Allows an admin to approve or reject an AI-generated answer.

    Request body:
        - validation_status: 'approved' or 'rejected'
        - validation_note:   Optional explanation

    Returns:
        Updated message with validation fields set.
    """
    service = QAService(db)
    message = await service.validate_message(message_id, data, current_user.id)
    return ResponseBuilder.success(
        data=QAMessageOut.model_validate(message).model_dump(mode="json"),
        message=f"Message {data.validation_status} successfully.",
    )


# ─────────────────────────────────────────────────────────────────────────────
# ADMIN VIEWS
# ─────────────────────────────────────────────────────────────────────────────

# @router.get("/history", summary="All Q&A history (admin)")
# async def get_qa_history(
#     page:              int            = Query(default=1,    ge=1),
#     page_size:         int            = Query(default=10,   ge=1, le=100),
#     search:            Optional[str]  = Query(default=None, description="Search in question text"),
#     helpful:           Optional[bool] = Query(default=None),
#     validation_status: Optional[str]  = Query(default=None, pattern="^(pending|approved|rejected)$"),
#     document_id:       Optional[UUID] = Query(default=None),
#     category_id:       Optional[UUID] = Query(default=None),
#     user_id:           Optional[UUID] = Query(default=None),
#     sort_by:           str            = Query(default="created_at"),
#     sort_order:        str            = Query(default="desc", pattern="^(asc|desc)$"),
#     db: AsyncSession = Depends(get_db),
#     _=Depends(require_role("admin", "editor")),
# ):
#     """
#     Admin view: All Q&A messages across all users and sessions.

#     Query params:
#         - search:            Partial match on question text
#         - helpful:           true | false
#         - validation_status: pending | approved | rejected
#         - sort_by, sort_order, page, page_size: standard pagination
#     """
#     service = QAService(db)
#     items, total = await service.list_all_messages(
#         page, page_size, search, helpful, validation_status, document_id, category_id, user_id, sort_by, sort_order
#     )
#     out = [QAMessageListOut.model_validate(m).model_dump(mode="json") for m in items]
#     return ResponseBuilder.paginated(items=out, total=total, page=page, page_size=page_size)

@router.get("/history", summary="Q&A history")
async def get_qa_history(
    page:              int            = Query(default=1,    ge=1),
    page_size:         int            = Query(default=10,   ge=1, le=100),
    search:            Optional[str]  = Query(default=None, description="Search in question text"),
    helpful:           Optional[bool] = Query(default=None),
    validation_status: Optional[str]  = Query(default=None, pattern="^(pending|approved|rejected)$"),
    document_id:       Optional[UUID] = Query(default=None),
    category_id:       Optional[UUID] = Query(default=None),
    user_id:           Optional[UUID] = Query(default=None),
    sort_by:           str            = Query(default="created_at"),
    sort_order:        str            = Query(default="desc", pattern="^(asc|desc)$"),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Q&A history.

    Admin:
      - Can see all users' Q&A history.
      - Can optionally filter by user_id.

    Normal user/viewer:
      - Can only see their own Q&A history.
      - Any user_id passed from frontend is ignored.
    """

    service = QAService(db)

    role_name = current_user.role.name if current_user.role else "viewer"

    if role_name in ["admin"]:
        effective_user_id = user_id
    else:
        effective_user_id = current_user.id

    items, total = await service.list_all_messages(
        page,
        page_size,
        search,
        helpful,
        validation_status,
        document_id,
        category_id,
        effective_user_id,
        sort_by,
        sort_order,
    )

    out = [
        QAMessageListOut.model_validate(m).model_dump(mode="json")
        for m in items
    ]

    return ResponseBuilder.paginated(
        items=out,
        total=total,
        page=page,
        page_size=page_size,
    )


@router.get("/unanswered", summary="Unanswered questions needing admin review")
async def get_unanswered_questions(
    page:       int           = Query(default=1,  ge=1),
    page_size:  int           = Query(default=10, ge=1, le=100),
    search:     Optional[str] = Query(default=None, description="Search in question text"),
    category_id: Optional[UUID] = Query(default=None),
    user_id:    Optional[UUID] = Query(default=None),
    sort_by:    str           = Query(default="created_at"),
    sort_order: str           = Query(default="desc", pattern="^(asc|desc)$"),
    db: AsyncSession = Depends(get_db),
    _=Depends(require_role("admin")),
):
    """
    Admin review list for questions that could not be answered
    confidently from the published knowledge base.
    """
    service = QAService(db)
    items, total = await service.list_unanswered_messages(
        page, page_size, search, category_id, user_id, sort_by, sort_order
    )
    out = [QAMessageListOut.model_validate(m).model_dump(mode="json") for m in items]
    return ResponseBuilder.paginated(items=out, total=total, page=page, page_size=page_size)


@router.get("/ai-logs", summary="AI call logs (Admin)")
async def get_ai_logs(
    page:       int           = Query(default=1,  ge=1),
    page_size:  int           = Query(default=10, ge=1, le=100),
    status:     Optional[str] = Query(default=None, pattern="^(success|failed)$"),
    provider:   Optional[str] = Query(default=None),
    sort_by:    str           = Query(default="created_at"),
    sort_order: str           = Query(default="desc", pattern="^(asc|desc)$"),
    db: AsyncSession = Depends(get_db),
    _=Depends(require_role("admin")),
):
    """
    Admin monitoring: All AI API call logs with token usage, response times, and errors.

    Query params:
        - status: 'success' | 'failed'
        - provider: 'Google Gemini' | 'Qwen/Qwen3-8B'
    """
    service = QAService(db)
    items, total = await service.list_ai_logs(page, page_size, status, provider, sort_by, sort_order)
    
    out = [AILogOut.model_validate(l).model_dump(mode="json") for l in items]
    return ResponseBuilder.paginated(items=out, total=total, page=page, page_size=page_size)
